-- 99Bricks: Saved Searches and Market Alerts
-- Run this in the Supabase SQL Editor.
--
-- What it's for: lets a logged-in buyer save a set of search filters
-- (property type, BHK, price range, facing, parking, road width, and an
-- optional map location + radius) from the homepage. Whenever an admin
-- approves a new listing (see app/admin/properties/page.tsx), the
-- /api/alerts/notify-matches route checks it against every active saved
-- search and drops a row into search_alerts for each match, which powers
-- the buyer-facing /alerts inbox and the unseen-count badge in the
-- account menu.

create table if not exists saved_searches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  filters jsonb not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists saved_searches_user_id_idx
  on saved_searches(user_id);

alter table saved_searches enable row level security;

create policy "Users can view their own saved searches"
  on saved_searches for select
  using (auth.uid() = user_id);

create policy "Users can create their own saved searches"
  on saved_searches for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own saved searches"
  on saved_searches for update
  using (auth.uid() = user_id);

create policy "Users can delete their own saved searches"
  on saved_searches for delete
  using (auth.uid() = user_id);


create table if not exists search_alerts (
  id bigint generated by default as identity primary key,
  saved_search_id bigint not null references saved_searches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id bigint not null references properties(id) on delete cascade,
  seen boolean not null default false,
  created_at timestamptz not null default now(),
  unique (saved_search_id, property_id)
);

create index if not exists search_alerts_user_id_idx
  on search_alerts(user_id);

alter table search_alerts enable row level security;

-- Alerts are only ever written by the server (via the service_role key in
-- /api/alerts/notify-matches), so there is intentionally no insert policy
-- here for regular users -- only select/update/delete of their own rows.

create policy "Users can view their own search alerts"
  on search_alerts for select
  using (auth.uid() = user_id);

create policy "Users can mark their own search alerts as seen"
  on search_alerts for update
  using (auth.uid() = user_id);

create policy "Users can dismiss their own search alerts"
  on search_alerts for delete
  using (auth.uid() = user_id);
